builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - freebsd
    - windows
    - linux
  goarch:
    - amd64
    - arm64
archive:
  replacements:
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
